# Advanced RAG Pipeline

In [1]:
import utils

import os
import openai
openai.api_key = utils.get_openai_api_key()

✅ In Answer Relevance, input prompt will be set to __record__.main_input or `Select.RecordInput` .
✅ In Answer Relevance, input response will be set to __record__.main_output or `Select.RecordOutput` .
✅ In Context Relevance, input prompt will be set to __record__.main_input or `Select.RecordInput` .
✅ In Context Relevance, input response will be set to __record__.app.query.rets.source_nodes[:].node.text .
✅ In Groundedness, input source will be set to __record__.app.query.rets.source_nodes[:].node.text .
✅ In Groundedness, input statement will be set to __record__.main_output or `Select.RecordOutput` .

In [2]:
from llama_index import SimpleDirectoryReader

documents = SimpleDirectoryReader(
    input_files=["./eBook-How-to-Build-a-Career-in-AI.pdf"]
).load_data()

In [3]:
print(type(documents), "\n")
print(len(documents), "\n")
print(type(documents[0]))
print(documents[0])

<class 'list'>

41

<class 'llama_index.schema.Document'>
Doc ID: bb86edaa-7040-4d3b-86bd-6cf897500d15
Text: PAGE 1Founder, DeepLearning.AICollected Insights from Andrew Ng
How to  Build Your Career in AIA Simple Guide

## Basic RAG pipeline

In [4]:
from llama_index import Document

document = Document(text="\n\n".join([doc.text for doc in documents]))

In [5]:
from llama_index import VectorStoreIndex
from llama_index import ServiceContext
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)
service_context = ServiceContext.from_defaults(
    llm=llm, embed_model="local:BAAI/bge-small-en-v1.5"
)
index = VectorStoreIndex.from_documents([document],
                                        service_context=service_context)

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

[nltk_data] Downloading package punkt to /tmp/llama_index...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [7]:
query_engine = index.as_query_engine()

In [8]:
response = query_engine.query(
    "What are steps to take when finding projects to build your experience?"
)
print(str(response))

Develop a side hustle, ensure the project will help you grow technically, collaborate with good teammates, and consider if the project can be a stepping stone to larger projects.

## Evaluation setup using TruLens

In [9]:
eval_questions = []
with open('eval_questions.txt', 'r') as file:
    for line in file:
        # Remove newline character and convert to integer
        item = line.strip()
        print(item)
        eval_questions.append(item)

What are the keys to building a career in AI?
How can teamwork contribute to success in AI?
What is the importance of networking in AI?
What are some good habits to develop for a successful career?
How can altruism be beneficial in building a career?
What is imposter syndrome and how does it relate to AI?
Who are some accomplished individuals who have experienced imposter syndrome?
What is the first step to becoming good at AI?
What are some common challenges in AI?
Is it normal to find parts of AI challenging?

In [10]:
# You can try your own question:
new_question = "What is the right AI job for me?"
eval_questions.append(new_question)

In [11]:
print(eval_questions)

['What are the keys to building a career in AI?', 'How can teamwork contribute to success in AI?', 'What is the importance of networking in AI?', 'What are some good habits to develop for a successful career?', 'How can altruism be beneficial in building a career?', 'What is imposter syndrome and how does it relate to AI?', 'Who are some accomplished individuals who have experienced imposter syndrome?', 'What is the first step to becoming good at AI?', 'What are some common challenges in AI?', 'Is it normal to find parts of AI challenging?', 'What is the right AI job for me?']

In [12]:
from trulens_eval import Tru
tru = Tru()

tru.reset_database()

🦑 Tru initialized with db url sqlite:///default.sqlite .
🛑 Secret keys may be written to the database. See the `database_redact_keys` option of `Tru` to prevent this.

For the classroom, we've written some of the code in helper functions inside a utils.py file.  
- You can view the utils.py file in the file directory by clicking on the "Jupyter" logo at the top of the notebook.
- In later lessons, you'll get to work directly with the code that's currently wrapped inside these helper functions, to give you more options to customize your RAG pipeline.

In [13]:
from utils import get_prebuilt_trulens_recorder

tru_recorder = get_prebuilt_trulens_recorder(query_engine,
                                             app_id="Direct Query Engine")

In [14]:
with tru_recorder as recording:
    for question in eval_questions:
        response = query_engine.query(question)

In [15]:
records, feedback = tru.get_records_and_feedback(app_ids=[])

In [16]:
records.head()

,app_id,app_json,type,record_id,input,output,tags,record_json,cost_json,perf_json,ts,Answer Relevance,Context Relevance,Groundedness,Answer Relevance_calls,Context Relevance_calls,Groundedness_calls,latency,total_tokens,total_cost
0,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_3a99c82b4e4f7718111898daf811658d,"""What are the keys to building a career in AI?""","""Learning foundational technical skills, worki...",-,"{""record_id"": ""record_hash_3a99c82b4e4f7718111...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-09T19:49:24.726462"", ""...",2026-06-09T19:49:28.608292,1.0,1.00,0.9,[{'args': {'prompt': 'What are the keys to bui...,[{'args': {'prompt': 'What are the keys to bui...,"[{'args': {'source': 'PAGE 1Founder, DeepLearn...",3,2066,0.003123
1,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_2d336632eef62220a854f2375bd7dc28,"""How can teamwork contribute to success in AI?""","""Teamwork can contribute to success in AI by a...",-,"{""record_id"": ""record_hash_2d336632eef62220a85...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-09T19:49:28.724281"", ""...",2026-06-09T19:49:29.938150,0.9,0.50,1.0,[{'args': {'prompt': 'How can teamwork contrib...,[{'args': {'prompt': 'How can teamwork contrib...,[{'args': {'source': 'Hopefully the previous c...,1,1693,0.002573
2,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_d378e8378587b8f83f230ee56c2d5e59,"""What is the importance of networking in AI?""","""Networking is crucial in AI as it helps indiv...",-,"{""record_id"": ""record_hash_d378e8378587b8f83f2...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-09T19:49:30.049763"", ""...",2026-06-09T19:49:31.829949,1.0,0.50,NaN,[{'args': {'prompt': 'What is the importance o...,[{'args': {'prompt': 'What is the importance o...,NaN,1,1694,0.002576
3,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_e7ad7ff2401125d7536eb008c6f4d73b,"""What are some good habits to develop for a su...","""Developing good habits in areas such as eatin...",-,"{""record_id"": ""record_hash_e7ad7ff2401125d7536...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-09T19:49:31.937393"", ""...",2026-06-09T19:49:32.893347,1.0,0.95,NaN,[{'args': {'prompt': 'What are some good habit...,[{'args': {'prompt': 'What are some good habit...,NaN,0,1631,0.002465
4,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_d5d8b710b873b93ab1ec0254929db9ed,"""How can altruism be beneficial in building a ...","""Helping others during your own career journey...",-,"{""record_id"": ""record_hash_d5d8b710b873b93ab1e...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-09T19:49:32.998993"", ""...",2026-06-09T19:49:33.713489,1.0,NaN,NaN,[{'args': {'prompt': 'How can altruism be bene...,NaN,NaN,0,1610,0.002423

In [17]:
# launches on http://localhost:8501/
tru.run_dashboard()

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.

Accordion(children=(VBox(children=(VBox(children=(Label(value='STDOUT'), Output())), VBox(children=(Label(valu…

Dashboard started at https://s172-29-91-126p38560.lab-aws-production.deeplearning.ai/ .

## Advanced RAG pipeline

### 1. Sentence Window retrieval

In [18]:
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)

In [19]:
from utils import build_sentence_window_index

sentence_index = build_sentence_window_index(
    document,
    llm,
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="sentence_index"
)

In [20]:
from utils import get_sentence_window_query_engine

sentence_window_engine = get_sentence_window_query_engine(sentence_index)

config.json:   0%|          | 0.00/799 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

In [21]:
window_response = sentence_window_engine.query(
    "how do I get started on a personal project in AI?"
)
print(str(window_response))

To get started on a personal project in AI, you can begin by identifying a project that aligns with your career goals and interests. It is important to choose a project that is responsible, ethical, and beneficial to people. Once you have selected a project, you can follow the steps outlined in the chapters provided, such as scoping the project, executing it with an eye towards career development, and building a portfolio that demonstrates skill progression. By following these guidelines, you can embark on a personal AI project that not only enhances your skills but also makes a positive impact in the field.

In [22]:
tru.reset_database()

tru_recorder_sentence_window = get_prebuilt_trulens_recorder(
    sentence_window_engine,
    app_id = "Sentence Window Query Engine"
)

In [23]:
for question in eval_questions:
    with tru_recorder_sentence_window as recording:
        response = sentence_window_engine.query(question)
        print(question)
        print(str(response))

What are the keys to building a career in AI?
Learning foundational technical skills, working on projects, finding a job, and being part of a supportive community are the keys to building a career in AI.
How can teamwork contribute to success in AI?
Teammates play a crucial role in the success of AI projects. Working collaboratively with colleagues who are dedicated, continuously learning, and focused on building AI for the benefit of all can positively influence individual performance. The ability to work effectively in a team, leverage diverse skills and insights, and collectively steer projects towards success is essential in the field of AI.
What is the importance of networking in AI?
Networking in AI is crucial as it can provide valuable insights, guidance, and opportunities from individuals who have experience in the field. By connecting with professionals in AI through informational interviews or events like Pie & AI, individuals can gain knowledge about the industry, potential career paths, and current trends. This networking can also help in building relationships that may lead to future job opportunities or collaborations within the AI field.
What are some good habits to develop for a successful career?
Developing good habits in areas such as eating, exercise, sleep, personal relationships, work, learning, and self-care can help individuals move forward in their careers while maintaining their health.
How can altruism be beneficial in building a career?
Helping others and aiming to lift them during one's own career journey can lead to achieving better outcomes for oneself.
What is imposter syndrome and how does it relate to AI?
Imposter syndrome is a phenomenon where individuals doubt their accomplishments and have a persistent fear of being exposed as a fraud. In the context of AI, newcomers to the field may experience imposter syndrome, feeling like they do not truly belong in the AI community despite their success. This can be a common experience for many individuals in AI, including talented professionals like Sheryl Sandberg, Michelle Obama, Tom Hanks, and Mike Cannon-Brookes.
Who are some accomplished individuals who have experienced imposter syndrome?
Former Facebook COO Sheryl Sandberg, U.S. first lady Michelle Obama, actor Tom Hanks, and Atlassian co-CEO Mike Cannon-Brookes are some accomplished individuals who have experienced imposter syndrome.
What is the first step to becoming good at AI?
Identifying possible roles and conducting informational interviews.
What are some common challenges in AI?
Common challenges in AI include the evolving nature of technologies, the need to constantly keep up-to-date with changing technology, the difficulty in estimating project timelines and return on investment, the iterative nature of AI projects leading to challenges in project management, the necessity to collaborate with stakeholders lacking expertise in AI, and the ongoing struggle with technical challenges and mistakes that may arise during AI work.
Is it normal to find parts of AI challenging?
It is normal to find parts of AI challenging.
What is the right AI job for me?
The right AI job for you can be found by utilizing a simple framework to start your AI job search, building a portfolio of projects that demonstrate skill progression, and conducting informational interviews to find the job that aligns with your career goals.

In [24]:
tru.get_leaderboard(app_ids=[])

,Context Relevance,Answer Relevance,Groundedness,latency,total_cost
app_id,,,,,
Sentence Window Query Engine,0.48,1.0,0.626667,1.363636,0.000805

In [25]:
# launches on http://localhost:8501/
tru.run_dashboard()

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.
Dashboard already running at path: https://s172-29-91-126p38560.lab-aws-production.deeplearning.ai/

### 2. Auto-merging retrieval

In [26]:
from utils import build_automerging_index

automerging_index = build_automerging_index(
    documents,
    llm,
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="merging_index"
)

In [27]:
from utils import get_automerging_query_engine

automerging_query_engine = get_automerging_query_engine(
    automerging_index,
)

In [28]:
auto_merging_response = automerging_query_engine.query(
    "How do I build a portfolio of AI projects?"
)
print(str(auto_merging_response))

> Merging 1 nodes into parent node.
> Parent node id: 410ad466-9f7c-4f06-b786-add557f792e3.
> Parent node text: PAGE 21Building a Portfolio of
Projects that Shows
Skill Progression CHAPTER 6
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: ba6e71e4-79d2-4a24-9ce2-2da6ea038329.
> Parent node text: PAGE 21Building a Portfolio of
Projects that Shows
Skill Progression CHAPTER 6
PROJECTS

Building a portfolio of AI projects involves showcasing a progression from simple to complex undertakings over time. It is important to be able to communicate your thinking effectively to demonstrate the value of your work and gain trust from others. Identifying ideas that are worth working on is a crucial skill for an AI architect, and gaining experience through working on projects in various industries can help in building a strong portfolio.

In [29]:
tru.reset_database()

tru_recorder_automerging = get_prebuilt_trulens_recorder(automerging_query_engine,
                                                         app_id="Automerging Query Engine")

In [30]:
for question in eval_questions:
    with tru_recorder_automerging as recording:
        response = automerging_query_engine.query(question)
        print(question)
        print(response)

A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function BaseQueryEngine.query at 0x7f824aff76d0>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.
A new object of type <class 'llama_index.retrievers.auto_merging_retriever.AutoMergingRetriever'> at 0x7f81c833b160 is calling an instrumented method <function BaseRetriever.retrieve at 0x7f824aff6a70>. The path of this call may be incorrect.
Guessing path of new object is app.retriever based on other object (0x7f81d8191de0) using this function.
A new object of type <class 'llama_index.indices.vector_store.retrievers.retriever.VectorIndexRetriever'> at 0x7f81c833b0a0 is calling an instrumented method <function BaseRetriever.retrieve at 0x7f824aff6a70>. The path of this call may be incorrect.
Guessing path of new object is app.retriever based on other object (0x7f81d8191de0) using this function.

> Merging 2 nodes into parent node.
> Parent node id: 1ab352ec-d2c8-4b89-b649-300ef38332a2.
> Parent node text: PAGE 3Table of
ContentsIntroduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to Ca...

> Merging 1 nodes into parent node.
> Parent node id: 05c2ceba-3b1f-4ca0-ad89-3558c883a08a.
> Parent node text: PAGE 3Table of
ContentsIntroduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to Ca...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function CompactAndRefine.get_response at 0x7f824a4ef5b0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.llm_predictor.base.LLMPredictor'> at 0x7f81d0280100 is calling an instrumented method <function LLMPredictor.predict at 0x7f82574a91b0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer.service_context.llm_predictor based on other object (0x7f81f09c65c0) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

What are the keys to building a career in AI?
The keys to building a career in AI include learning foundational technical skills, working on projects, finding a job, and being part of a community. Additionally, collaborating with others, influencing, and being influenced by team members are critical aspects for success in AI.

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

How can teamwork contribute to success in AI?
Teamwork can contribute to success in AI by allowing individuals to work together in a collaborative environment. This enables them to leverage each other's strengths, share knowledge and expertise, and collectively tackle large projects more effectively than working alone. The ability to collaborate, influence, and be influenced by others is crucial in the field of AI, emphasizing the importance of teamwork in achieving career success.
> Merging 3 nodes into parent node.
> Parent node id: 4136c5c9-6f43-49f3-a52a-18b43d250fd6.
> Parent node text: PAGE 35Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more comple...

> Merging 1 nodes into parent node.
> Parent node id: 74a2bafd-561b-4b26-b9d4-46298a6aede2.
> Parent node text: PAGE 35Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more comple...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

What is the importance of networking in AI?
Networking in AI is crucial as it helps individuals build a strong professional network within the industry. This network can provide support, guidance, and opportunities for career advancement. By connecting with others in the field, individuals can gain valuable insights, access resources, and potentially open doors to new roles or projects.
> Merging 2 nodes into parent node.
> Parent node id: 0af04fde-7897-4a59-bef0-e0c6eb4551f2.
> Parent node text: PAGE 36Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
on...

> Merging 2 nodes into parent node.
> Parent node id: b415a079-76c6-45aa-bc41-00f78c1ac8a8.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

> Merging 1 nodes into parent node.
> Parent node id: 8b6a6549-2740-4736-a162-f70b9f36f28b.
> Parent node text: PAGE 36Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
on...

> Merging 1 nodes into parent node.
> Parent node id: 1dcd9ac7-d938-49da-9352-1f68d9e9138e.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

What are some good habits to develop for a successful career?
Good habits to develop for a successful career include habits related to eating, exercise, sleep, personal relationships, work, learning, and self-care. These habits can help individuals move forward in their careers while also maintaining their health and well-being.
> Merging 2 nodes into parent node.
> Parent node id: 22a2b004-3e15-4202-90ba-ad08fe2120ff.
> Parent node text: PAGE 30Finding someone to interview isn’t always easy, but many people who are in senior position...

> Merging 1 nodes into parent node.
> Parent node id: 9afdbf77-9ad7-493c-a59f-088d1204059c.
> Parent node text: PAGE 30Finding someone to interview isn’t always easy, but many people who are in senior position...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

How can altruism be beneficial in building a career?
Altruism can be beneficial in building a career by creating a positive impact on others, fostering strong relationships within one's network, and potentially leading to opportunities for growth and advancement through the support and guidance received from those who have been helped.
> Merging 5 nodes into parent node.
> Parent node id: e2ccdee0-b175-4502-80d1-f008eec185c2.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: ed57dd68-6d5a-4182-81c5-92988a1464ca.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 3 nodes into parent node.
> Parent node id: 31273bca-74ff-4396-b10c-597ba536dfb8.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

> Merging 1 nodes into parent node.
> Parent node id: 988f8197-9ace-45d5-aba4-f3b6d79c185b.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: 9d57beca-b6f1-41e5-bb72-db10c16d4ba1.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: 822d7bfb-4024-4753-af66-06593d3097f9.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

What is imposter syndrome and how does it relate to AI?
Imposter syndrome is when individuals doubt their accomplishments and have a persistent fear of being exposed as a fraud, despite evidence of their competence. In the context of AI, newcomers to the field may experience imposter syndrome due to the technical complexity and the presence of highly capable individuals. It is highlighted that even accomplished people in the AI community have faced imposter syndrome at some point. The message conveyed is that struggling with challenges in AI is a common experience and should not deter individuals from pursuing a career in the field.
> Merging 3 nodes into parent node.
> Parent node id: e2ccdee0-b175-4502-80d1-f008eec185c2.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: ed57dd68-6d5a-4182-81c5-92988a1464ca.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 3 nodes into parent node.
> Parent node id: 31273bca-74ff-4396-b10c-597ba536dfb8.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

> Merging 1 nodes into parent node.
> Parent node id: 988f8197-9ace-45d5-aba4-f3b6d79c185b.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: 9d57beca-b6f1-41e5-bb72-db10c16d4ba1.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: 822d7bfb-4024-4753-af66-06593d3097f9.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

Who are some accomplished individuals who have experienced imposter syndrome?
Sheryl Sandberg, Michelle Obama, Tom Hanks, and Mike Cannon-Brookes are some accomplished individuals who have experienced imposter syndrome.

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

What is the first step to becoming good at AI?
The first step to becoming good at AI is to suck at it.

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

What are some common challenges in AI?
Some common challenges in AI include the highly iterative nature of AI projects, uncertainty in planning due to not knowing how long it will take to achieve target accuracy, technical challenges faced by individuals working on AI projects, and feelings of imposter syndrome experienced by those entering the AI community.
> Merging 3 nodes into parent node.
> Parent node id: e2ccdee0-b175-4502-80d1-f008eec185c2.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: 988f8197-9ace-45d5-aba4-f3b6d79c185b.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f816018f1c0 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f8245e4eb00>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f81d81930a0) using this function.

Is it normal to find parts of AI challenging?
It is normal to find parts of AI challenging.
> Merging 1 nodes into parent node.
> Parent node id: 0313ad16-2c23-454a-af4b-fac9c9f42c73.
> Parent node text: PAGE 31Finding the Right
AI Job for YouCHAPTER 9
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 7c3e9743-1de2-4c91-99d9-1e139cc324cf.
> Parent node text: If you’re leaving
a job, exit gracefully. Give your employer ample notice, give your full effort...

> Merging 1 nodes into parent node.
> Parent node id: 6e7e3423-28c2-453e-a59f-3b7a3fe698fb.
> Parent node text: PAGE 28Using Informational
Interviews to Find
the Right JobCHAPTER 8
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 5435119f-a908-4535-ae72-7f49fa1b6424.
> Parent node text: PAGE 31Finding the Right
AI Job for YouCHAPTER 9
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 0383e2d7-3286-4e03-a39b-b983d157ba4f.
> Parent node text: PAGE 28Using Informational
Interviews to Find
the Right JobCHAPTER 8
JOBS

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f816018f130 is calling an instrumented method <function Refine.get_response at 0x7f8249923370>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f81d8193010) using this function.

What is the right AI job for me?
The right AI job for you may depend on whether you are looking to switch roles, industries, or both. If you are seeking your first job in AI, it may be easier to transition by switching either roles or industries rather than attempting both simultaneously.

In [31]:
tru.get_leaderboard(app_ids=[])

,Context Relevance,Answer Relevance,Groundedness,latency,total_cost
app_id,,,,,
Automerging Query Engine,0.721429,1.0,0.690476,2.363636,0.000863

In [32]:
# launches on http://localhost:8501/
tru.run_dashboard()

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.
Dashboard already running at path: https://s172-29-91-126p38560.lab-aws-production.deeplearning.ai/